config/routes.rb
Rails.application.routes.draw do
  resources :listings
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :listings
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :category
  enum condition: {damaged: 0, poor: 1, good: 2, excellent: 3, mint: 4}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:username, :email, :password, :password_confirmation)}

            devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:name, :email, :password, :current_password)}
        end
    
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_form_vars, only: [:new, :edit]
  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = current_user.listings.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:user_id, :category_id, :title, :condition, :price, :description, :sold)
    end

    def set_form_vars
      @categories = Category.all
      @condition = Listing.conditions.keys
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
        def select_alert_subclass(input)
        case input
        when 'notice'
        return 'info'
        when 'sucess'
            return 'sucess'
        when 'error'
            return 'danger'
        when 'alert'
            return 'warning'
        else 
            return 'info'
        end
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
    def select_alert_subclass(input)
        case input
        when 'notice'
            return 'info'
        when 'sucess'
            return 'sucess'
        when 'error'
            return 'danger'
        when 'alert'
            return 'warning'
        else
            return 'info'
        end
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nfleabay</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% flash.each do|key,value| %>
      <div class="alert alert-<%= select_alert_subclass(key)%> alert-dismissable fade show" role="alert">
        <%=value%>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true"> &times; </span>
        </button>
      </div>
    <% end %>
    <%= render '/shared/navbar' %> 
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group mb-3 ml-2">
    <%= form.label :category_id, class:"col form-label" %>
    <%= form.select :category_id, @categories.map {|c| [c.name, c.id]}, class: "form-select" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :title, class:"form-label" %>
    <%= form.text_field :title %>
  </div>

  <h5 class="mb-2"> Condition </h5>

  <div class="form-ckeck form-check-line mb-3">
    <% @condition.each do |option| %>
      <%= form.label :condition, option.capitalize, class: "form-label mr-1" %>
      <%= form.radio_button :condition, option, class: "mr-2" %>
    <% end %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :price, class:"form-label" %>
    <%= form.number_field :price %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :description, class:"form-label" %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Category</th>
      <th>Title</th>
      <th>Condition</th>
      <th>Price</th>
      <th>Description</th>
      <th>Sold</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.user_id %></td>
        <td><%= listing.category_id %></td>
        <td><%= listing.title %></td>
        <td><%= listing.condition %></td>
        <td><%= listing.price %></td>
        <td><%= listing.description %></td>
        <td><%= listing.sold %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p>
  <strong>User:</strong>
  <%= @listing.user_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @listing.category.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @listing.title %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @listing.condition %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @listing.sold %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/pages/home.html.erb
<h1> Welcome to Fleabay </h1>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md sticky-top">
    <div class="container-fluid">
        <%= link_to "Flebay", root_path, class:"nav-link" %>
    </div>
    <ul class="navbar-nav mr-5-lg" >
        <li class="nav-item">
            <%= link_to "All clothes", listings_path, class: "nav-link" %>
        </li>    
        <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to "Create a listing", new_listing_path, class: "nav-link" %>
        </li>  

        <li class="nav-item">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>  
        <%else%> 
         <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        </li>  

        <li class="nav-item">
            <%= link_to "Log Out", new_user_registration_path, class: "nav-link" %>
        </li>  
        <%end%>  
    </ul>
</nav>